name = "blink"
main = "worker/src/index.js"
compatibility_date = "2024-04-01"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "blink-db"
database_id = "8559d8e6-0b54-4c9d-894e-735f92c2609a"

# Durable Object Binding (Real-time Engine)
[[durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "ChatRoom"

[[migrations]]
tag = "v1"
new_classes = ["ChatRoom"]

# R2 Bucket Binding (File Storage)
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "blink-assets"
